version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  I-Have-Code:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Code has arrived
          command: |
            ls -la
            echo '^^^ This should show up'
  Run-Tests-With-Node:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: install and run tests
          command: |
            npm install && npm run test
      - codecov/upload:
          file: "./coverage/clover.xml"
          token: 3494ac91-cb31-4ec7-9b38-01831069b044
workflows:
  version: 2
  Example-Workflow:
    jobs:
      - I-Have-Code
      - Run-Tests-With-Node
